ALTER TABLE users ADD COLUMN IF NOT EXISTS display_name VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar VARCHAR(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS cycle_override INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS notify_days INTEGER DEFAULT 3;
